name: Build Parcel Plugin

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'gx-bangsong/SmartspacerPlugins'
          path: 'SmartspacerPlugins'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x SmartspacerPlugins/gradlew
      
      - name: Create local.properties
        run: touch SmartspacerPlugins/local.properties

      - name: Build with Gradle
        run: |
          cd SmartspacerPlugins
          ./gradlew :plugin-parcel:assembleDebug

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qweather-plugin
          path: SmartspacerPlugins/apks/plugin-parcel-debug.apk
