name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your workflow code
      - name: Checkout the code
        uses: actions/checkout@v2
      
      # Step 2: Set up Java Development Kit (JDK 11)
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      # Step 3: Clone the GKUIClock project
      # This will clone the repository into a directory named "GKUIClock"
      - name: Clone project
        run: git clone --depth=1 https://github.com/gx-bangsong/GKUIClock/
      
      # Step 4: Build the application
      # The 'working-directory' is now correctly set to './GKUIClock'
      - name: Build the app
        working-directory: ./GKUIClock
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
      
      # Step 5: Upload the compiled APK file as a workflow artifact
      # The path is updated to look for APKs inside the 'GKUIClock' directory
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Dialer-build-apk
          path: GKUIClock/app/build/outputs/apk/debug/*.apk
